export const formatKey = (value: string) =>
		value
			.split("_")
			.map((part) => (part.length <= 3 ? part.toUpperCase() : part[0].toUpperCase() + part.slice(1)))
			.join(" ");

export const STAT_LABELS: Record<string, string> = {
		appearances: "Appearances",
		matches: "Matches",
		min: "Minutes",
		minutes: "Minutes",
		points: "Points",
		wins: "Wins",
		draws: "Draws",
		losses: "Losses",
		goal_diff: "Goal Difference",
		goals_for: "Goals For",
		goals_against: "Goals Against",
		gf: "Goals For",
		ga: "Goals Against",
		goals: "Goals",
		assists: "Assists",
		xg: "xG",
		xga: "xGA",
		npxg: "npxG",
		npxgd: "npxG Diff",
		poss: "Possession %",
		attendance: "Attendance",
		standard_gls: "Goals",
		standard_sh: "Shots",
		standard_sot: "Shots on Target",
		standard_sot_2: "Shots on Target %",
		standard_g_sh: "Goals per Shot",
		standard_g_sot: "Goals per SoT",
		standard_dist: "Shot Distance",
		standard_fk: "Free Kick Shots",
		standard_pk: "Penalty Goals",
		standard_pkatt: "Penalty Attempts",
		expected_xg: "xG",
		expected_npxg: "npxG",
		expected_xag: "xA",
		expected_npxg_sh: "npxG per Shot",
		expected_g_xg: "Goals minus xG",
		expected_np_g_xg: "Non-penalty Goals minus xG",
		performance_gls: "Goals",
		performance_ast: "Assists",
		performance_pk: "Penalty Goals",
		performance_pkatt: "Penalty Attempts",
		performance_sh: "Shots",
		performance_sot: "Shots on Target",
		performance_crdy: "Yellow Cards",
		performance_crdr: "Red Cards",
		performance_touches: "Touches",
		performance_tkl: "Tackles",
		performance_int: "Interceptions",
		performance_blocks: "Blocks",
		performance_fls: "Fouls Committed",
		performance_fld: "Fouls Drawn",
		performance_off: "Offsides",
		performance_crs: "Crosses",
		performance_tklw: "Tackles Won",
		performance_pkwon: "Penalties Won",
		performance_pkcon: "Penalties Conceded",
		performance_og: "Own Goals",
		performance_recov: "Ball Recoveries",
		performance_2crdy: "Second Yellow Cards",
		performance_sota: "Shots on Target Against",
		performance_ga: "Goals Against",
		performance_saves: "Saves",
		performance_save: "Save %",
		performance_cs: "Clean Sheets",
		performance_psxg: "Post-shot xG",
		performance_psxg_2: "PSxG per SoT",
		shot_stopping_sota: "Shots on Target Against",
		shot_stopping_ga: "Goals Against",
		shot_stopping_saves: "Saves",
		shot_stopping_save_pct: "Save %",
		shot_stopping_psxg: "Post-shot xG",
		shot_stopping_psxg_diff: "PSxG minus GA",
		shot_stopping_psxg_2: "PSxG per SoT",
		shot_stopping_psxg_per_sot: "PSxG per SoT",
		sca_sca: "Shot-Creating Actions",
		sca_gca: "Goal-Creating Actions",
		sca_types_sca: "Shot-Creating Actions",
		sca_types_passlive: "SCA from Live-ball Pass",
		sca_types_passdead: "SCA from Dead-ball Pass",
		sca_types_to: "SCA from Take-on",
		sca_types_sh: "SCA from Shot",
		sca_types_fld: "SCA from Foul Drawn",
		sca_types_def: "SCA from Defensive Action",
		gca_types_gca: "Goal-Creating Actions",
		gca_types_passlive: "GCA from Live-ball Pass",
		gca_types_passdead: "GCA from Dead-ball Pass",
		gca_types_to: "GCA from Take-on",
		gca_types_sh: "GCA from Shot",
		gca_types_fld: "GCA from Foul Drawn",
		gca_types_def: "GCA from Defensive Action",
		passes_cmp: "Passes Completed",
		passes_att: "Passes Attempted",
		passes_cmp_2: "Pass Completion %",
		passes_prgp: "Progressive Passes",
		total_cmp: "Passes Completed",
		total_att: "Passes Attempted",
		total_cmp_2: "Pass Completion %",
		total_totdist: "Total Pass Distance",
		total_prgdist: "Progressive Pass Distance",
		short_cmp: "Short Passes Completed",
		short_att: "Short Passes Attempted",
		short_cmp_2: "Short Pass Completion %",
		medium_cmp: "Medium Passes Completed",
		medium_att: "Medium Passes Attempted",
		medium_cmp_2: "Medium Pass Completion %",
		long_cmp: "Long Passes Completed",
		long_att: "Long Passes Attempted",
		long_cmp_2: "Long Pass Completion %",
		ast: "Assists",
		xag: "xAG",
		xa: "xA",
		kp: "Key Passes",
		"1_3": "Passes into Final Third",
		ppa: "Passes into Penalty Area",
		crspa: "Crosses into Penalty Area",
		prgp: "Progressive Passes",
		att: "Passes Attempted",
		pass_types_live: "Live-ball Passes",
		pass_types_dead: "Dead-ball Passes",
		pass_types_fk: "Free Kick Passes",
		pass_types_tb: "Through Balls",
		pass_types_sw: "Switches",
		pass_types_crs: "Crosses",
		pass_types_ti: "Throw-ins",
		pass_types_ck: "Corner Kicks",
		corner_kicks_in: "In-swinging Corners",
		corner_kicks_out: "Out-swinging Corners",
		corner_kicks_str: "Straight Corners",
		outcomes_cmp: "Completed Passes",
		outcomes_off: "Offside Passes",
		outcomes_blocks: "Blocked Passes",
		penalty_kicks_pkatt: "Penalties Faced",
		penalty_kicks_pka: "Penalties Allowed",
		penalty_kicks_pksv: "Penalties Saved",
		penalty_kicks_pkm: "Penalties Missed",
		launched_cmp: "Launches Completed",
		launched_att: "Launches Attempted",
		launched_cmp_2: "Launch Completion %",
		passes_att_gk: "Goalkeeper Passes Attempted",
		passes_thr: "Throws",
		passes_launch: "Launches",
		passes_avglen: "Avg Pass Length",
		goal_kicks_att: "Goal Kicks Attempted",
		goal_kicks_launch: "Goal Kicks Launched",
		goal_kicks_avglen: "Avg Goal Kick Length",
		crosses_opp: "Crosses Faced",
		crosses_stp: "Crosses Stopped",
		crosses_stp_2: "Crosses Stopped %",
		sweeper_opa: "Defensive Actions Outside Pen Area",
		sweeper_avgdist: "Avg Sweeper Distance",
		tackles_tkl: "Tackles",
		tackles_tklw: "Tackles Won",
		tackles_def_3rd: "Tackles in Def Third",
		tackles_mid_3rd: "Tackles in Mid Third",
		tackles_att_3rd: "Tackles in Att Third",
		challenges_tkl: "Dribbles Tackled",
		challenges_att: "Dribbles Challenged",
		challenges_tkl_2: "Dribbles Tackled %",
		challenges_lost: "Dribbles Bypassed",
		blocks_blocks: "Blocks",
		blocks_sh: "Shots Blocked",
		blocks_pass: "Passes Blocked",
		int: "Interceptions",
		tkl_int: "Tackles + Interceptions",
		clr: "Clearances",
		err: "Errors Leading to Shots",
		touches_touches: "Touches",
		touches_def_pen: "Touches in Def Pen Area",
		touches_def_3rd: "Touches in Def Third",
		touches_mid_3rd: "Touches in Mid Third",
		touches_att_3rd: "Touches in Att Third",
		touches_att_pen: "Touches in Att Pen Area",
		touches_live: "Live-ball Touches",
		take_ons_att: "Take-ons Attempted",
		take_ons_succ: "Take-ons Completed",
		take_ons_succ_2: "Take-on Success %",
		take_ons_tkld: "Tackled on Take-ons",
		take_ons_tkld_2: "Tackled on Take-ons %",
		carries_carries: "Carries",
		carries_totdist: "Total Carry Distance",
		carries_prgdist: "Progressive Carry Distance",
		carries_prgc: "Progressive Carries",
		carries_1_3: "Carries into Final Third",
		carries_cpa: "Carries into Pen Area",
		carries_mis: "Miscontrols",
		carries_dis: "Dispossessed",
		receiving_rec: "Passes Received",
		receiving_prgr: "Progressive Passes Received",
		aerial_duels_won: "Aerial Duels Won",
		aerial_duels_lost: "Aerial Duels Lost",
		aerial_duels_won_2: "Aerial Duels Won %"
	};

export const STAT_DESCRIPTIONS: Record<string, string> = {
		appearances: "Matches played.",
		matches: "Matches played.",
		min: "Minutes played.",
		minutes: "Minutes played.",
		points: "Total points earned.",
		wins: "Matches won.",
		draws: "Matches drawn.",
		losses: "Matches lost.",
		goals: "Goals scored.",
		assists: "Assists recorded.",
		goal_diff: "Goals for minus goals against.",
		goals_for: "Goals scored by the team.",
		goals_against: "Goals conceded.",
		gf: "Goals scored by the team.",
		ga: "Goals conceded.",
		xg: "Expected goals (xG).",
		xga: "Expected goals against (xGA).",
		npxg: "Non-penalty expected goals (npxG).",
		npxgd: "Non-penalty expected goals difference.",
		poss: "Share of possession.",
		attendance: "Match attendance.",
		standard_gls: "Goals scored.",
		standard_sh: "Shots taken.",
		standard_sot: "Shots on target.",
		standard_sot_2: "Shots on target percentage.",
		standard_g_sh: "Goals per shot.",
		standard_g_sot: "Goals per shot on target.",
		standard_dist: "Average shot distance.",
		standard_fk: "Shots from free kicks.",
		standard_pk: "Penalty goals scored.",
		standard_pkatt: "Penalty attempts.",
		expected_xg: "Expected goals (xG).",
		expected_npxg: "Non-penalty expected goals (npxG).",
		expected_xag: "Expected assists (xA).",
		expected_npxg_sh: "Non-penalty xG per shot.",
		expected_g_xg: "Goals minus expected goals.",
		expected_np_g_xg: "Non-penalty goals minus expected goals.",
		performance_gls: "Goals scored.",
		performance_ast: "Assists recorded.",
		performance_pk: "Penalty goals scored.",
		performance_pkatt: "Penalty kicks attempted.",
		performance_sh: "Shots taken.",
		performance_sot: "Shots on target.",
		performance_crdy: "Yellow cards.",
		performance_crdr: "Red cards.",
		performance_touches: "Touches recorded.",
		performance_tkl: "Tackles recorded.",
		performance_int: "Interceptions recorded.",
		performance_blocks: "Blocks recorded.",
		performance_fls: "Fouls committed.",
		performance_fld: "Fouls drawn.",
		performance_off: "Offsides recorded.",
		performance_crs: "Crosses attempted.",
		performance_tklw: "Tackles won.",
		performance_pkwon: "Penalties won.",
		performance_pkcon: "Penalties conceded.",
		performance_og: "Own goals.",
		performance_recov: "Ball recoveries.",
		performance_2crdy: "Second yellow cards.",
		performance_sota: "Shots on target faced.",
		performance_ga: "Goals conceded by the keeper.",
		performance_saves: "Saves made.",
		performance_save: "Save percentage.",
		performance_cs: "Clean sheets.",
		performance_psxg: "Post-shot expected goals faced.",
		performance_psxg_2: "Post-shot xG per shot on target.",
		shot_stopping_sota: "Shots on target faced by the keeper.",
		shot_stopping_ga: "Goals conceded while the keeper is on the pitch.",
		shot_stopping_saves: "Saves made by the keeper.",
		shot_stopping_save_pct: "Share of shots on target saved.",
		shot_stopping_psxg: "Post-shot expected goals faced.",
		shot_stopping_psxg_diff: "Post-shot xG minus goals conceded.",
		shot_stopping_psxg_2: "Post-shot xG per shot on target faced.",
		shot_stopping_psxg_per_sot: "Post-shot xG per shot on target faced.",
		sca_sca: "Shot-creating actions.",
		sca_gca: "Goal-creating actions.",
		sca_types_sca: "Shot-creating actions.",
		sca_types_passlive: "SCAs from live-ball passes.",
		sca_types_passdead: "SCAs from dead-ball passes.",
		sca_types_to: "SCAs from take-ons.",
		sca_types_sh: "SCAs from shots.",
		sca_types_fld: "SCAs from fouls drawn.",
		sca_types_def: "SCAs from defensive actions.",
		gca_types_gca: "Goal-creating actions.",
		gca_types_passlive: "GCAs from live-ball passes.",
		gca_types_passdead: "GCAs from dead-ball passes.",
		gca_types_to: "GCAs from take-ons.",
		gca_types_sh: "GCAs from shots.",
		gca_types_fld: "GCAs from fouls drawn.",
		gca_types_def: "GCAs from defensive actions.",
		passes_cmp: "Passes completed.",
		passes_att: "Passes attempted.",
		passes_cmp_2: "Pass completion percentage.",
		passes_prgp: "Progressive passes completed.",
		total_cmp: "Passes completed.",
		total_att: "Passes attempted.",
		total_cmp_2: "Pass completion percentage.",
		total_totdist: "Total pass distance.",
		total_prgdist: "Progressive pass distance.",
		short_cmp: "Short passes completed.",
		short_att: "Short passes attempted.",
		short_cmp_2: "Short pass completion percentage.",
		medium_cmp: "Medium passes completed.",
		medium_att: "Medium passes attempted.",
		medium_cmp_2: "Medium pass completion percentage.",
		long_cmp: "Long passes completed.",
		long_att: "Long passes attempted.",
		long_cmp_2: "Long pass completion percentage.",
		ast: "Assists recorded.",
		xag: "Expected assisted goals (xAG).",
		xa: "Expected assists (xA).",
		kp: "Key passes.",
		"1_3": "Passes into the final third.",
		ppa: "Passes into the penalty area.",
		crspa: "Crosses into the penalty area.",
		prgp: "Progressive passes completed.",
		att: "Passes attempted.",
		pass_types_live: "Live-ball passes.",
		pass_types_dead: "Dead-ball passes.",
		pass_types_fk: "Free kick passes.",
		pass_types_tb: "Through balls.",
		pass_types_sw: "Switches of play.",
		pass_types_crs: "Crosses.",
		pass_types_ti: "Throw-ins.",
		pass_types_ck: "Corner kicks taken.",
		corner_kicks_in: "In-swinging corners.",
		corner_kicks_out: "Out-swinging corners.",
		corner_kicks_str: "Straight corners.",
		outcomes_cmp: "Completed passes.",
		outcomes_off: "Offside passes.",
		outcomes_blocks: "Blocked passes.",
		penalty_kicks_pkatt: "Penalty kicks faced.",
		penalty_kicks_pka: "Penalty goals allowed.",
		penalty_kicks_pksv: "Penalties saved.",
		penalty_kicks_pkm: "Penalties missed by opponent.",
		launched_cmp: "Long passes completed by the keeper.",
		launched_att: "Long passes attempted by the keeper.",
		launched_cmp_2: "Long pass completion percentage.",
		passes_att_gk: "Goalkeeper passes attempted.",
		passes_thr: "Throws by the keeper.",
		passes_launch: "Launches by the keeper.",
		passes_avglen: "Average pass length.",
		goal_kicks_att: "Goal kicks attempted.",
		goal_kicks_launch: "Goal kicks launched.",
		goal_kicks_avglen: "Average goal kick length.",
		crosses_opp: "Crosses faced.",
		crosses_stp: "Crosses stopped.",
		crosses_stp_2: "Crosses stopped percentage.",
		sweeper_opa: "Defensive actions outside the penalty area.",
		sweeper_avgdist: "Average distance of defensive actions.",
		tackles_tkl: "Tackles made.",
		tackles_tklw: "Tackles won.",
		tackles_def_3rd: "Tackles in the defensive third.",
		tackles_mid_3rd: "Tackles in the middle third.",
		tackles_att_3rd: "Tackles in the attacking third.",
		challenges_tkl: "Dribblers tackled.",
		challenges_att: "Dribblers challenged.",
		challenges_tkl_2: "Dribblers tackled percentage.",
		challenges_lost: "Dribbles completed against.",
		blocks_blocks: "Blocks recorded.",
		blocks_sh: "Shots blocked.",
		blocks_pass: "Passes blocked.",
		int: "Interceptions recorded.",
		tkl_int: "Tackles plus interceptions.",
		clr: "Clearances.",
		err: "Errors leading to shots.",
		touches_touches: "Touches recorded.",
		touches_def_pen: "Touches in defensive penalty area.",
		touches_def_3rd: "Touches in defensive third.",
		touches_mid_3rd: "Touches in middle third.",
		touches_att_3rd: "Touches in attacking third.",
		touches_att_pen: "Touches in attacking penalty area.",
		touches_live: "Live-ball touches.",
		take_ons_att: "Take-ons attempted.",
		take_ons_succ: "Successful take-ons.",
		take_ons_succ_2: "Take-on success percentage.",
		take_ons_tkld: "Tackled during take-ons.",
		take_ons_tkld_2: "Tackled percentage on take-ons.",
		carries_carries: "Carries recorded.",
		carries_totdist: "Total carry distance.",
		carries_prgdist: "Progressive carry distance.",
		carries_prgc: "Progressive carries.",
		carries_1_3: "Carries into the final third.",
		carries_cpa: "Carries into the penalty area.",
		carries_mis: "Miscontrols.",
		carries_dis: "Times dispossessed.",
		receiving_rec: "Passes received.",
		receiving_prgr: "Progressive passes received.",
		aerial_duels_won: "Aerial duels won.",
		aerial_duels_lost: "Aerial duels lost.",
		aerial_duels_won_2: "Aerial duels won percentage."
	};

const TOKEN_EXPANSIONS: Record<string, string> = {
	sota: "shots on target against",
	psxg: "post-shot expected goals",
	ga: "goals against",
	saves: "saves",
	save: "save",
	pct: "percentage",
	avg: "average",
	dist: "distance",
	pk: "penalty kicks",
	pka: "penalty kicks allowed",
	pksv: "penalty kicks saved",
	pkm: "penalty kicks missed",
	opp: "opponent",
	gca: "goal-creating actions",
	sca: "shot-creating actions"
};

const expandTokens = (value: string) =>
	value
		.split("_")
		.map((token) => TOKEN_EXPANSIONS[token] ?? token)
		.join(" ");

const autoDescription = (key: string) => {
	const normalized = key.toLowerCase();
	if (normalized.startsWith("shot_stopping_")) {
		const suffix = normalized.replace("shot_stopping_", "");
		return `Goalkeeper shot-stopping: ${expandTokens(suffix)}.`;
	}
	return `FBref stat for ${expandTokens(normalized)}.`;
};

export const statLabel = (key: string) => STAT_LABELS[key] ?? STAT_LABELS[key.toLowerCase()] ?? formatKey(key);
export const statDescription = (key: string) =>
	STAT_DESCRIPTIONS[key] ??
	STAT_DESCRIPTIONS[key.toLowerCase()] ??
	autoDescription(key);
